### ISSUE TITLE
Files in tree view incorrectly named in some cases

### ISSUE THREAD

**Issue by ociappara** [CybercentreCanada/assemblyline-ui#583]
### Issue:

If you submit a compressed file for analysis (only observed it with gzip) the SHA256 of the child element is the same as the SHA256 of the parent. 

<img width="549" alt="image" src="https://user-images.githubusercontent.com/101556967/214525961-2061edab-f452-457e-ac19-bf5424db4ece.png">

### Expected:

Each element should use its own SHA256 as the name.
For instance in the above example it should looking as follows:

```
44ead0ca5769b7e237691f1db5b560c3f883a150ade5640cefa2327e117453f4 (parent Zip)
    275a021bbfb6489e54d471899f7db9d1663fc695ec2fe2a2c4538aabf651fd0f (child text file)
```

### Steps to reproduce:

Submit 44ead0ca5769b7e237691f1db5b560c3f883a150ade5640cefa2327e117453f4, notice both parent and child elements have the same name.

**Comment by gdesmar** [comment]
I think you are mixing two things in your ticket. You first say that the sha256 of the child is the same as the parent, and then that you expect the name to be the sha256 of the file. I would first want to point out that the name of the children file ends with a tilde, so it is not a sha256. It is the name extracted from the call to 7zip in the Extract module:
![image](https://user-images.githubusercontent.com/75089569/214600276-ecda6ef1-9375-4418-9702-b64820ae1cee.png)
If the children file was name "eicar_file" this would be the name showing up in the file tree.

Now, I believe not showing the name in the file tree would make it harder for users to quickly get a feel of the files in the archive, for example 3b35d3028c35181669e6a8993164633cd8ea81664f27b5b9ef8387c78c181a5e:
![image](https://user-images.githubusercontent.com/75089569/214602065-6ecc556a-4739-4d2a-a8a4-86db30c4d167.png)

This is another good example that should raise an eyebrow, and an heuristic in metapeek, 6a6634a6754be1fdcb3a84e5a32a6bc1171b3975a85aa2f9e6deb5f3bfdf9d8b:
![image](https://user-images.githubusercontent.com/75089569/214602508-35acb62d-c932-4219-82a5-f16f081b67ce.png)

I'll leave this ticket open in case we want to implement a userprofile option to always show the sha256 instead of the extracted file name in the file tree. Do you think it would be more useful than seeing the extracted file name? I feel that submissions with 25 files may be harder to navigate if you can only rely on the identified type to figure out which file is which. The real file's sha256 can always be accessed in the file identification section once you click on it in the file tree.

**Comment by cccs-sgaron** [comment]
We do not dictate what the file name is but the gzip file tells us. So as @gdesmar was saying extract has done what it was supposed to do and I don't think we should interfere with that. The file tree shows the name of the file not the sha256.

**Comment by ociappara** [comment]
Thanks everyone for your comments, it was something a few of our folks brought up, I agree with your explanation and happy to close this bug.
